# Generated by Django 4.2 on 2024-09-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_views_count'),
        ('accounts', '0002_rename_image_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookmarked_articles',
            field=models.ManyToManyField(blank=True, related_name='bookmarkers', to='articles.article'),
        ),
    ]
